apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: '11.7.0'
  values:
    postgresqlPassword: secret-password
    postgresqlUsername: user
    postgresqlDatabase: my-database
